apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pv5by4t1m-nodejs 
  janus-idp.io/tekton: pv5by4t1m-nodejs
  backstage.io/kubernetes-id: pv5by4t1m-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pv5by4t1m-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml